name = "youtube-scraping-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[env.development]
vars = { ENVIRONMENT = "development", DEBUG_MODE = "true" }

[env.production]
vars = { ENVIRONMENT = "production", DEBUG_MODE = "false" }

[[kv_namespaces]]
binding = "CACHE"
id = "youtube_cache_namespace"
preview_id = "youtube_cache_namespace_preview"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "rate_limits_namespace"
preview_id = "rate_limits_namespace_preview"

[vars]
# These will be set in Cloudflare dashboard or via wrangler secret
# YOUTUBE_API_KEY = "your-youtube-api-key"
# OAUTH_CLIENT_ID = "your-oauth-client-id"
# OAUTH_CLIENT_SECRET = "your-oauth-client-secret"

[build]
command = "npm run build"

[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"